name: dpkg-deb
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: just setup
        uses: extractions/setup-just@v2
      
      - name: go setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: install dev-tools 
        run: just dev-tools

      - name: run just build and package command 
        run: just deb-pkg

      - uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: build/packages/*.deb

  download-and-install:
    needs: build-and-upload
    name: download-and-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - run: |
          ls

      - name: install .deb
        run: |
          sudo dpkg -i debian-package/*
      
      - name: run version command
        run: |
          revisio version