name: dpkg-deb
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2
      
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: install dev-tools 
        run: just dev-tools

      - name: run just build and debian package commands 
        run: just deb-pkg

      - uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: build/packages/*.deb

  download-and-install:
    needs: build-and-upload
    name: download-and-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4

      - name: install debian package
        run: |
          sudo dpkg -i debian-package/*
      
      - name: run version command
        run: |
          revisio version

      - name: run create command
        run: |
          revisio create -k hello -v world

      - name: run read command with verbosity
        run: |
          revisio read -k hello --verbose